# Generated by Django 2.0.6 on 2018-06-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Курс у замовленні', 'verbose_name_plural': 'Курси у замовленні'},
        ),
    ]
